package cartelerapeliculasgui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 * @see <a href="https://github.com/Esguvi/CarteleraPeliculasGUI">GitHub</a> 
 * @author Esguvi - esguvioficial@gmail.com
*/

public class GUICartelera extends javax.swing.JFrame {

    private ArrayList<Pelicula> peliculas;
    private static final String archivoPeliculas = "PeliculasDeEsguvi.txt";
    /**
     * Creates new form GUI
     */
    public GUICartelera() {
        peliculas = new ArrayList<>();
        initComponents();
        cargarPeliculas();
    }

    private void cargarPeliculas() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(archivoPeliculas))) {
            peliculas = (ArrayList<Pelicula>) ois.readObject();
        } catch (FileNotFoundException fnfe) {
            System.out.println("No se encontró el fichero, se creará uno nuevo al guardar.");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (IOException ioe) {
            ioe.getMessage();
        }
    }
    
    public void guardarPeliculas() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(archivoPeliculas))) {
            oos.writeObject(peliculas);
        } catch (IOException e) {
            e.getMessage();
        }
    }

    public void añadirPelicula(Pelicula pelicula) {
        peliculas.add(pelicula);

        File file = new File("PeliculasDeEsguvi.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo de películas no existe", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file))) {
                oos.writeObject(peliculas);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de películas", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    public void eliminarPelicula(Pelicula pelicula) {
        peliculas.remove(pelicula);

        File file = new File("PeliculasDeEsguvi.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo de películas no existe", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file))) {
                oos.writeObject(peliculas);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de películas", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    public ArrayList<Pelicula> getPeliculas() {
        return peliculas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblSombra = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnAñadirPelicula = new javax.swing.JButton();
        btnEliminarPelicula = new javax.swing.JButton();
        btnMostrarPeliculas = new javax.swing.JButton();
        btnListarInfoPelicula = new javax.swing.JButton();
        btnComparaPeliPremio = new javax.swing.JButton();
        btnComparaPeliDuracion = new javax.swing.JButton();
        btnSalirYGuardar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarteleraEsguvi");
        setResizable(false);

        panelInicio.setMinimumSize(new java.awt.Dimension(960, 540));
        panelInicio.setPreferredSize(new java.awt.Dimension(960, 540));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(201, 45, 45));
        panelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        lblSombra.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblSombra.setForeground(new java.awt.Color(255, 255, 255));
        lblSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSombra.setText("CARTELERA");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CARTELERA");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(lblSombra, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(lblSombra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelInicio.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 80));

        btnAñadirPelicula.setBackground(new java.awt.Color(0, 0, 0));
        btnAñadirPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirPelicula.setText("AÑADIR PELÍCULA");
        btnAñadirPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPeliculaActionPerformed(evt);
            }
        });
        panelInicio.add(btnAñadirPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 260, 40));

        btnEliminarPelicula.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPelicula.setText("ELIMINAR PELÍCULA");
        btnEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliculaActionPerformed(evt);
            }
        });
        panelInicio.add(btnEliminarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 40));

        btnMostrarPeliculas.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrarPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPeliculas.setText("MOSTRAR PELÍCULAS");
        btnMostrarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPeliculasActionPerformed(evt);
            }
        });
        panelInicio.add(btnMostrarPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 40));

        btnListarInfoPelicula.setBackground(new java.awt.Color(0, 0, 0));
        btnListarInfoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        btnListarInfoPelicula.setText("LISTAR INFORMACIÓN PELÍCULA");
        btnListarInfoPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarInfoPeliculaActionPerformed(evt);
            }
        });
        panelInicio.add(btnListarInfoPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 260, 40));

        btnComparaPeliPremio.setBackground(new java.awt.Color(0, 0, 0));
        btnComparaPeliPremio.setForeground(new java.awt.Color(255, 255, 255));
        btnComparaPeliPremio.setText("COMPARA PELICULAS - DIRECTOR");
        btnComparaPeliPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparaPeliPremioActionPerformed(evt);
            }
        });
        panelInicio.add(btnComparaPeliPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, 40));

        btnComparaPeliDuracion.setBackground(new java.awt.Color(0, 0, 0));
        btnComparaPeliDuracion.setForeground(new java.awt.Color(255, 255, 255));
        btnComparaPeliDuracion.setText("COMPARA PELICULAS - DURACIÓN");
        btnComparaPeliDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparaPeliDuracionActionPerformed(evt);
            }
        });
        panelInicio.add(btnComparaPeliDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 260, 40));

        btnSalirYGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalirYGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirYGuardar.setText("SALIR Y GUARDAR CARTELERA");
        btnSalirYGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirYGuardarActionPerformed(evt);
            }
        });
        panelInicio.add(btnSalirYGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 260, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelerapeliculasgui/img/fondo.jpg"))); // NOI18N
        panelInicio.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelInicio.getAccessibleContext().setAccessibleName("CarteleraEsguvi");
        panelInicio.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPeliculasActionPerformed
        GUIMostrarPeliculas mostrarPeliculas = new GUIMostrarPeliculas(this);
        mostrarPeliculas.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnMostrarPeliculasActionPerformed

    private void btnEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliculaActionPerformed
        GUIEliminarPelicula eliminarPelicula = new GUIEliminarPelicula(this);
        eliminarPelicula.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnEliminarPeliculaActionPerformed

    private void btnAñadirPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPeliculaActionPerformed
        GUICrearPelicula crearPelicula = new GUICrearPelicula(this);
        crearPelicula.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAñadirPeliculaActionPerformed

    private void btnListarInfoPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarInfoPeliculaActionPerformed
        GUIInformacionPelicula infoPelicula = new GUIInformacionPelicula(this);
        infoPelicula.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnListarInfoPeliculaActionPerformed

    private void btnComparaPeliPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparaPeliPremioActionPerformed
        Collections.sort(peliculas, new ComparaPelisPorDirector());
        JOptionPane.showMessageDialog(this, "Películas ordenadas correctamente por su duración.", "Ordenar por duración", JOptionPane.INFORMATION_MESSAGE);

        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(archivoPeliculas))) {
            oos.writeObject(peliculas);
            dispose();
            GUIMostrarPeliculas mostrarPeliculas = new GUIMostrarPeliculas();
            mostrarPeliculas.setVisible(true);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnComparaPeliPremioActionPerformed

    private void btnComparaPeliDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparaPeliDuracionActionPerformed
        Collections.sort(peliculas, new ComparaPelisPorDuracion());
        JOptionPane.showMessageDialog(this, "Películas ordenadas correctamente por su duración.", "Ordenar por duración", JOptionPane.INFORMATION_MESSAGE);

        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(archivoPeliculas))) {
            oos.writeObject(peliculas);
            dispose();
            GUIMostrarPeliculas mostrarPeliculas = new GUIMostrarPeliculas();
            mostrarPeliculas.setVisible(true);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnComparaPeliDuracionActionPerformed

    private void btnSalirYGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirYGuardarActionPerformed
        guardarPeliculas();
        JOptionPane.showMessageDialog(this, "Cartelera guardada/actualizada exitosamente.");
        System.exit(0);
    }//GEN-LAST:event_btnSalirYGuardarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUICartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirPelicula;
    private javax.swing.JButton btnComparaPeliDuracion;
    private javax.swing.JButton btnComparaPeliPremio;
    private javax.swing.JButton btnEliminarPelicula;
    private javax.swing.JButton btnListarInfoPelicula;
    private javax.swing.JButton btnMostrarPeliculas;
    private javax.swing.JButton btnSalirYGuardar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblSombra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
